# Generated by Django 5.1.5 on 2025-02-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinemauser',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='cinemauser',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
