# Generated by Django 5.1.5 on 2025-03-02 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_session_date_session_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='testDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
