# Generated by Django 5.1.5 on 2025-03-02 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_session_testdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='session',
            name='testDate',
        ),
        migrations.AddField(
            model_name='session',
            name='sessionDate',
            field=models.DateTimeField(db_column='session_date', default=datetime.datetime.now),
        ),
    ]
